=== i3Cheese/camunda_and_evalai/camunda/src/main/resources/xsd/newOrganizationApplication.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
					 targetNamespace="camundakotlin"
					 xmlns="camundakotlin"
					 elementFormDefault="qualified"
>
	<xs:element name="newOrganizationApplication">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="organizationInfo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" />
							<xs:element name="address" type="xs:string" />
							<xs:element name="phone" type="xs:string" />
							<xs:element name="email" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publicInformation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" />
							<xs:element name="url" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="organizationContactPerson">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" />
							<xs:element name="position" type="xs:string" />
							<xs:element name="phone" type="xs:string" />
							<xs:element name="email" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== i3Cheese/camunda_and_evalai/camunda/src/main/resources/xsd/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<newOrganizationApplication xmlns="camundakotlin"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="camundakotlin  NewOrganizationApplication.xsd"
>
	<organizationInfo>
		<name>Pepsico</name>
		<address>Here</address>
		<phone>+78000000000</phone>
		<email>example@example.com</email>
	</organizationInfo>
	<organizationContactPerson>
		<name>Cheese</name>
		<position>CTO</position>
		<phone>+78000000000</phone>
		<email>example@example.com</email>
	</organizationContactPerson>
</newOrganizationApplication>
