=== i3Cheese/camunda_and_evalai/camunda/schema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="a"
	xmlns="a"
	elementFormDefault="qualified"
>
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="child" type="xs:string" />
				<xs:element name="list" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="reg">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[0-9]{3}" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="date" type="xs:date" />
				<xs:element name="number" type="xs:integer" />
				<xs:element name="decimal" type="xs:decimal" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== i3Cheese/camunda_and_evalai/camunda/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="a"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="a schema.xsd"
>
	<child>123</child>
	<list>1</list>
	<list>2</list>
	<reg>123</reg>
	<date>2019-01-01</date>
	<number>123</number>
	<decimal>123.123</decimal>
</root>
